name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{" ${{ secrets.DOCKER_USERNAME }}"}}
          password: ${{" ${{ secrets.DOCKER_PASSWORD }}"}}

      - name: Build Docker image
        run: docker build -t ${{" ${{ secrets.DOCKER_USERNAME }}"}}/fastapi-repo:latest .

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{" ${{ secrets.DOCKER_USERNAME }}"}}
          password: ${{" ${{ secrets.DOCKER_PASSWORD }}"}}

      - name: Build Docker image
        run: docker build -t ${{" ${{ secrets.DOCKER_USERNAME }}"}}/fastapi-repo:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{" ${{ secrets.DOCKER_USERNAME }}"}}/fastapi-repo:latest
